"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Loader2, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/ui/status-badge";

type Message = { id: string; sender_type: "customer" | "admin" | "bot"; body: string; created_at: string };
type SupportCase = { id: string; case_number: string; subject: string | null; topic: string; status: string; priority: string; created_at: string; tracking_code?: string | null; deliveries?: { delivery_code?: string; status?: string } | null; support_messages: Message[] };

export function CaseConversation({ caseId }: { caseId: string }) {
  const [item, setItem] = useState<SupportCase | null>(null); const [draft, setDraft] = useState(""); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = async () => { const response = await fetch(`/api/support/cases/${caseId}`, { cache: "no-store" }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || "Could not load this support case."); setItem(result.case); };
  useEffect(() => { void load().catch((cause) => setError(cause instanceof Error ? cause.message : "Could not load this support case.")).finally(() => setLoading(false)); }, [caseId]);
  async function reply(event: FormEvent) { event.preventDefault(); const body = draft.trim(); if (body.length < 2) return setError("Write a short reply before sending."); setSending(true); setError(null); try { const response = await fetch(`/api/support/cases/${caseId}/messages`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || "Could not send your reply."); setDraft(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not send your reply."); } finally { setSending(false); } }
  if (loading) return <section className="section-wrap py-10"><p className="text-sm font-bold text-slate-600"><Loader2 className="mr-2 inline h-4 w-4 animate-spin" />Loading support case…</p></section>;
  if (!item) return <section className="section-wrap py-10"><p className="text-sm font-bold text-red-700">{error || "Support case not found."}</p></section>;
  const closed = item.status === "closed";
  return <section className="section-wrap py-6 pb-28 sm:py-10"><Link href="/support/cases" className="inline-flex items-center gap-2 text-sm font-black text-fleet-navy"><ArrowLeft className="h-4 w-4" />My cases</Link><div className="mt-5 rounded-fleet border border-fleet-line bg-white p-5 shadow-lift"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.14em] text-fleet-ember">{item.case_number}</p><h1 className="mt-2 text-2xl font-black text-fleet-night">{item.subject || item.topic}</h1><p className="mt-2 text-sm font-semibold text-slate-600">Created {new Date(item.created_at).toLocaleString()}{item.deliveries?.delivery_code ? ` · Delivery ${item.deliveries.delivery_code}` : item.tracking_code ? ` · Delivery ${item.tracking_code}` : ""}</p></div><StatusBadge tone={closed || item.status === "resolved" ? "green" : item.priority === "urgent" ? "red" : "amber"}>{item.status.replaceAll("_", " ")}</StatusBadge></div><div className="mt-6 grid gap-3">{item.support_messages.map((message) => <article key={message.id} className={`max-w-[90%] rounded-fleet p-3 text-sm leading-6 ${message.sender_type === "admin" ? "bg-fleet-night text-white" : "bg-fleet-paper text-slate-700"}`}><strong className="block text-xs font-black uppercase tracking-[0.1em] opacity-80">{message.sender_type === "admin" ? "Fast Fleets 360 Support" : message.sender_type === "bot" ? "Support guidance" : "You"}</strong><p className="mt-1 whitespace-pre-wrap">{message.body}</p><time className="mt-2 block text-[0.65rem] font-bold opacity-70">{new Date(message.created_at).toLocaleString()}</time></article>)}</div></div>{closed ? <p className="mt-4 rounded-fleet bg-fleet-paper p-4 text-sm font-semibold text-slate-600">This case is closed. Create a new case if you need further help.</p> : <form onSubmit={reply} className="fixed inset-x-0 bottom-0 z-50 border-t border-fleet-line bg-white/95 p-3 backdrop-blur sm:static sm:mt-4 sm:rounded-fleet sm:border"><div className="section-wrap flex gap-2 sm:max-w-none sm:px-0"><textarea value={draft} onChange={(event) => setDraft(event.target.value)} className="form-textarea min-h-12 flex-1" maxLength={2000} placeholder="Reply to support" /><Button type="submit" disabled={sending}>{sending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}<span className="sr-only sm:not-sr-only">Send</span></Button></div>{error ? <p className="section-wrap mt-2 px-0 text-xs font-bold text-red-700">{error}</p> : null}</form>}</section>;
}
