"use client";

import { useEffect, useState } from "react";
import { Loader2 } from "lucide-react";

type Application = { id: string; status: string; residential_area: string; preferred_operating_zone: string; employment_preference: string; experience_notes?: string | null; rejection_reason?: string | null; user?: { full_name?: string | null; email?: string | null; phone?: string | null } | null };
const next: Record<string, string[]> = { submitted: ["screening", "rejected"], screening: ["assessment_invited", "rejected"], assessment_invited: ["assessment_passed", "rejected"], assessment_passed: ["approved", "rejected"], approved: ["rider_activated", "suspended"], rider_activated: ["suspended"] };

export function CyclistApplicationOperations() {
  const [applications, setApplications] = useState<Application[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState<string | null>(null);
  const load = () => fetch("/api/admin/cyclist-applications", { cache: "no-store" }).then(async r => { const p = await r.json(); if (!r.ok) throw new Error(p.error || "Could not load cyclist applications."); setApplications(p.applications); });
  useEffect(() => { load().catch(e => setMessage(e.message)).finally(() => setLoading(false)); }, []);
  async function transition(id: string, status: string) { const reason = status === "rejected" ? window.prompt("Rejection reason:")?.trim() || "" : ""; if (status === "rejected" && reason.length < 4) return; const response = await fetch("/api/admin/cyclist-applications", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status, reason }) }); const result = await response.json().catch(() => ({})); if (!response.ok) return setMessage(result.error || "Could not update cyclist application."); setMessage("Cyclist application updated."); load().catch(() => undefined); }
  if (loading) return <main className="section-wrap grid min-h-[60vh] place-items-center"><Loader2 className="h-7 w-7 animate-spin" /></main>;
  return <main className="section-wrap max-w-5xl px-4 py-7 sm:px-6"><span className="text-xs font-black uppercase tracking-[.16em] text-fleet-ember">Operations</span><h1 className="mt-2 text-3xl font-black text-fleet-night">Cyclist applications</h1><p className="mt-2 font-semibold text-slate-600">Recruitment intent feeds the canonical rider profile only when you activate the applicant.</p>{message ? <p className="mt-4 rounded-fleet bg-fleet-paper p-3 text-sm font-bold">{message}</p> : null}<div className="mt-6 grid gap-4">{applications.length ? applications.map(application => <article key={application.id} className="rounded-[20px] border border-fleet-line bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-black text-fleet-night">{application.user?.full_name || "Applicant"}</h2><p className="text-sm font-semibold text-slate-500">{application.user?.email || application.user?.phone || "Contact protected"}</p></div><span className="rounded-full bg-fleet-paper px-3 py-1 text-xs font-black uppercase">{application.status.replaceAll("_", " ")}</span></div><p className="mt-3 text-sm font-semibold text-slate-600">{application.residential_area} · {application.preferred_operating_zone} · {application.employment_preference.replaceAll("_", " ")}</p>{application.experience_notes ? <p className="mt-2 text-sm leading-6 text-slate-600">{application.experience_notes}</p> : null}<div className="mt-4 flex flex-wrap gap-2">{(next[application.status] || []).map(status => <button key={status} onClick={() => transition(application.id, status)} className="rounded-lg border border-fleet-line px-3 py-2 text-xs font-black text-fleet-night">{status.replaceAll("_", " ")}</button>)}</div></article>) : <p className="rounded-fleet bg-fleet-paper p-4 font-bold text-slate-600">No cyclist applications yet.</p>}</div></main>;
}
