"use client";

import { useEffect, useState } from "react";
import { Loader2 } from "lucide-react";

type Campaign = { id: string; title: string; slug: string; campaign_type: string; reward_amount_ngn: number; is_active: boolean; starts_at?: string | null; ends_at?: string | null };
type Reward = { id: string; amount_ngn: number; status: string; referral?: { referrer?: { full_name?: string | null }; referred?: { full_name?: string | null }; campaign?: { title?: string | null } } };

export function ReferralOperations() {
  const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [rewards, setRewards] = useState<Reward[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState<string | null>(null);
  const load = () => fetch("/api/admin/referrals", { cache: "no-store" }).then(async r => { const p = await r.json(); if (!r.ok) throw new Error(p.error || "Could not load referrals."); setCampaigns(p.campaigns); setRewards(p.rewards); });
  useEffect(() => { load().catch(e => setMessage(e.message)).finally(() => setLoading(false)); }, []);
  async function updateReward(rewardId: string, action: "hold" | "release" | "reverse") { const reason = action === "release" ? "" : window.prompt(`Reason to ${action} this referral reward:`)?.trim() || ""; if (action !== "release" && reason.length < 4) return; const response = await fetch("/api/admin/referrals", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rewardId, action, reason }) }); const data = await response.json().catch(() => ({})); if (!response.ok) return setMessage(data.error || "Could not update reward."); setMessage("Referral reward updated."); load().catch(() => undefined); }
  async function saveCampaign(campaign: Campaign) { const response = await fetch("/api/admin/referrals", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: "campaign", id: campaign.id, isActive: campaign.is_active, rewardAmountNgn: campaign.reward_amount_ngn, startsAt: campaign.starts_at || null, endsAt: campaign.ends_at || null }) }); const data = await response.json().catch(() => ({})); if (!response.ok) return setMessage(data.error || "Could not save campaign."); setMessage("Campaign saved. New referrals use the updated configuration."); load().catch(() => undefined); }
  if (loading) return <main className="section-wrap grid min-h-[60vh] place-items-center"><Loader2 className="h-7 w-7 animate-spin" /></main>;
  return <main className="section-wrap max-w-6xl px-4 py-7 sm:px-6"><span className="text-xs font-black uppercase tracking-[.16em] text-fleet-ember">Operations</span><h1 className="mt-2 text-3xl font-black text-fleet-night">Refer &amp; Win</h1><p className="mt-2 font-semibold text-slate-600">Campaign controls, pending rewards, holds, and immutable transfer history.</p>{message ? <p className="mt-4 rounded-fleet bg-fleet-paper p-3 text-sm font-bold">{message}</p> : null}<section className="mt-6 grid gap-4 md:grid-cols-2">{campaigns.map(c => <article key={c.id} className="rounded-[20px] border border-fleet-line bg-white p-4"><strong className="text-lg text-fleet-night">{c.title}</strong><label className="form-field mt-3"><span className="form-label">Reward (NGN)</span><input type="number" className="form-input" value={c.reward_amount_ngn} onChange={e => setCampaigns(current => current.map(item => item.id === c.id ? { ...item, reward_amount_ngn: Number(e.target.value) } : item))} /></label><label className="mt-3 flex gap-2 text-sm font-bold"><input type="checkbox" checked={c.is_active} onChange={e => setCampaigns(current => current.map(item => item.id === c.id ? { ...item, is_active: e.target.checked } : item))} /> Campaign active</label><button onClick={() => saveCampaign(c)} className="mt-4 h-10 rounded-xl bg-fleet-night px-4 text-sm font-black text-white">Save campaign</button></article>)}</section><section className="mt-7 overflow-hidden rounded-[20px] border border-fleet-line bg-white"><div className="border-b border-fleet-line p-4"><h2 className="font-black text-fleet-night">Latest referral rewards</h2></div><div className="divide-y divide-fleet-line">{rewards.map(reward => <div key={reward.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><strong className="block text-fleet-night">{reward.referral?.referrer?.full_name || "Referrer"} → {reward.referral?.referred?.full_name || "Member"}</strong><span className="text-sm font-semibold text-slate-500">{reward.referral?.campaign?.title || "Referral"} · ₦{Number(reward.amount_ngn).toLocaleString("en-NG")} · {reward.status}</span></div><div className="flex gap-2">{["pending", "available"].includes(reward.status) ? <button className="rounded-lg border border-amber-200 px-3 py-2 text-xs font-black text-amber-800" onClick={() => updateReward(reward.id, "hold")}>Hold</button> : null}{reward.status === "held" ? <button className="rounded-lg border border-emerald-200 px-3 py-2 text-xs font-black text-emerald-700" onClick={() => updateReward(reward.id, "release")}>Release</button> : null}{["pending", "available", "held"].includes(reward.status) ? <button className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-black text-rose-700" onClick={() => updateReward(reward.id, "reverse")}>Reverse</button> : null}</div></div>)}</div></section></main>;
}
