"use client";

import Link from "next/link";
import { AlertCircle, ChevronLeft, ChevronRight, Loader2, RefreshCw, Truck } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { StatusBadge } from "@/components/ui/status-badge";
import { createClient } from "@/lib/supabase/client";
import { formatDateTime } from "@/lib/format";

type Rider = { id: string; name: string; phone?: string | null; approval_status: string; operating_zone?: string | null; vehicle: string; online: boolean; available: boolean; busy: boolean; offline: boolean; location_status: "fresh" | "stale" | "unavailable"; location_updated_at?: string | null; asset?: { code: string; status: string; ownership: string; operating_state?: string | null; operating_zone?: string | null } | null; delivery?: { id: string; code: string; status: string; vehicle: string; accepted_at?: string | null; pickup?: string | null; destination?: string | null } | null };
type Payload = { riders: Rider[]; counts: { online: number; offline: number; available: number; busy: number; location_stale: number }; pagination: { page: number; page_size: number; total: number }; definitions: { available: string; busy: string; location_stale: string }; location_freshness_minutes: number };
const filters = [["all", "All riders"], ["online", "Online"], ["available", "Available"], ["busy", "Busy"], ["offline", "Offline"], ["stale", "Location stale"]] as const;

export function RiderFleetOperations() {
  const [payload, setPayload] = useState<Payload | null>(null); const [filter, setFilter] = useState("all"); const [vehicle, setVehicle] = useState(""); const [state, setState] = useState(""); const [search, setSearch] = useState(""); const [page, setPage] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async (silent = false) => { if (!silent) setLoading(true); const params = new URLSearchParams({ filter, page: String(page) }); if (vehicle) params.set("vehicle", vehicle); if (state.trim()) params.set("state", state.trim()); if (search.trim()) params.set("q", search.trim()); try { const response = await fetch(`/api/operations/riders?${params}`, { cache: "no-store" }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || "Could not load riders."); setPayload(result); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load riders."); } finally { if (!silent) setLoading(false); } }, [filter, page, vehicle, state, search]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const supabase = createClient(); let timer: ReturnType<typeof setTimeout> | null = null; const refresh = () => { if (timer) clearTimeout(timer); timer = setTimeout(() => void load(true), 500); }; const channel = supabase.channel("operations-riders") .on("postgres_changes", { event: "*", schema: "public", table: "rider_profiles" }, refresh) .on("postgres_changes", { event: "*", schema: "public", table: "rider_locations" }, refresh) .on("postgres_changes", { event: "*", schema: "public", table: "deliveries" }, refresh) .on("postgres_changes", { event: "*", schema: "public", table: "fleet_assets" }, refresh).subscribe(); return () => { if (timer) clearTimeout(timer); void supabase.removeChannel(channel); }; }, [load]);
  const changeFilter = (value: string) => { setFilter(value); setPage(0); };
  if (loading && !payload) return <main className="section-wrap py-10"><Card className="grid min-h-48 place-items-center"><Loader2 className="h-6 w-6 animate-spin" /></Card></main>;
  return <main className="section-wrap py-6 sm:py-10"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-xs font-black uppercase tracking-[.14em] text-fleet-ember">Internal · admin only</p><h1 className="mt-1 text-3xl font-black text-fleet-night">Rider &amp; Fleet Operations</h1><p className="mt-2 max-w-3xl text-sm font-semibold text-slate-600">Intentional rider availability, operational fleet assignments, active delivery state, and last reliable GPS — kept as separate signals.</p></div><div className="flex gap-2"><Link href="/operations"><Button variant="secondary">Operations home</Button></Link><Button variant="secondary" onClick={() => void load()}><RefreshCw className="h-4 w-4" />Refresh</Button></div></div>{error ? <div role="alert" className="mt-5 flex gap-2 rounded-fleet bg-amber-50 p-3 text-sm font-bold text-amber-800"><AlertCircle className="h-5 w-5" />{error}</div> : null}
    <div className="mt-6 grid gap-3 grid-cols-2 md:grid-cols-5"><Metric label="Online" value={payload?.counts.online || 0} /><Metric label="Available" value={payload?.counts.available || 0} /><Metric label="Busy" value={payload?.counts.busy || 0} /><Metric label="Offline" value={payload?.counts.offline || 0} /><Metric label="Location stale" value={payload?.counts.location_stale || 0} /></div>
    <Card className="mt-6 p-4"><div className="flex flex-wrap gap-2">{filters.map(([value, label]) => <button key={value} type="button" onClick={() => changeFilter(value)} className={`min-h-10 rounded-full px-3 text-sm font-black ${filter === value ? "bg-fleet-navy text-white" : "bg-slate-100 text-slate-700"}`}>{label}</button>)}</div><div className="mt-4 grid gap-3 md:grid-cols-3"><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(0); }} className="form-input" placeholder="Search rider name, phone or ID" aria-label="Search riders" /><select value={vehicle} onChange={(event) => { setVehicle(event.target.value); setPage(0); }} className="form-input" aria-label="Filter vehicle"><option value="">All vehicles</option><option value="bike">Bicycle</option><option value="motorcycle">Motorcycle</option><option value="car">Car</option><option value="van">Van</option></select><input value={state} onChange={(event) => { setState(event.target.value); setPage(0); }} className="form-input" placeholder="State or operating region" aria-label="Filter state or region" /></div></Card>
    <div className="mt-5 grid gap-3">{payload?.riders.map((rider) => <RiderCard key={rider.id} rider={rider} />) || null}{payload && !payload.riders.length ? <Card className="p-5 text-sm font-bold text-slate-600">No riders match these bounded server-side filters.</Card> : null}</div>
    {payload && payload.pagination.total > payload.pagination.page_size ? <div className="mt-5 flex items-center justify-between"><Button variant="secondary" disabled={page === 0} onClick={() => setPage(page - 1)}><ChevronLeft className="h-4 w-4" />Previous</Button><span className="text-sm font-bold text-slate-600">{page * payload.pagination.page_size + 1}–{Math.min(payload.pagination.total, (page + 1) * payload.pagination.page_size)} of {payload.pagination.total}</span><Button variant="secondary" disabled={(page + 1) * payload.pagination.page_size >= payload.pagination.total} onClick={() => setPage(page + 1)}>Next<ChevronRight className="h-4 w-4" /></Button></div> : null}
    {payload ? <p className="mt-5 text-xs font-semibold text-slate-500">{payload.definitions.available} {payload.definitions.location_stale}</p> : null}</main>;
}
function Metric({ label, value }: { label: string; value: number }) { return <Card className="p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-500">{label}</p><strong className="mt-1 block text-2xl text-fleet-night">{value}</strong></Card>; }
function RiderCard({ rider }: { rider: Rider }) { const status = rider.offline ? "Offline" : rider.busy ? "Online · Busy" : rider.available ? "Online · Available" : "Online"; const tone = rider.offline ? "slate" : rider.busy ? "amber" : "green"; return <Card className="p-4"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-black text-fleet-night">{rider.name}</h2><StatusBadge tone={tone as any}>{status}</StatusBadge>{rider.online && rider.location_status !== "fresh" ? <StatusBadge tone="amber">Location {rider.location_status}</StatusBadge> : null}</div><p className="mt-1 text-xs font-semibold text-slate-500">{rider.phone || "Phone not recorded"} · {rider.operating_zone || "Region not recorded"} · {rider.approval_status}</p><div className="mt-4 grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-4"><Info label="Vehicle" value={rider.vehicle} /><Info label="Asset" value={rider.asset ? `${rider.asset.code} · ${rider.asset.status}` : "No fleet asset"} /><Info label="Ownership" value={rider.asset?.ownership || "Not applicable"} /><Info label="Last location" value={rider.location_updated_at ? `${rider.location_status} · ${formatDateTime(rider.location_updated_at)}` : "Unavailable"} /></div>{rider.delivery ? <div className="mt-4 rounded-fleet bg-slate-50 p-3 text-sm"><div className="flex items-center gap-2 font-black text-fleet-night"><Truck className="h-4 w-4" />Current delivery {rider.delivery.code} · {rider.delivery.status.replaceAll("_", " ")}</div><p className="mt-1 text-xs font-semibold text-slate-600">Pickup: {rider.delivery.pickup || "Not recorded"} · Destination: {rider.delivery.destination || "Not recorded"}</p></div> : null}</div></div></Card>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-black uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 font-bold text-slate-700">{value}</p></div>; }
