"use client";

import { useEffect, useMemo, useState } from "react";
import { Loader2, PackagePlus, Pencil, RefreshCw, ShieldCheck, Store, WalletCards } from "lucide-react";
import { Button, LinkButton } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { formatMoney } from "@/lib/format";
import type { FastErrandsCategory } from "@/lib/fast-errands-catalog";

type Business = { id: string; business_name: string; operating_state?: string | null; pickup_address?: string | null };
type Errand = { id: string; errand_code: string; vendor_name: string; request_items: Array<{ text?: string }>; purchase_budget_ngn: number; delivery_fee_ngn: number; service_fee_ngn: number; customer_total_ngn: number; status: string; top_up_required_ngn: number; users?: { full_name?: string | null } | null; deliveries?: { dropoff_address?: string | null } | null };
const emptyCategory = { id: "", name: "", description: "", emoji: "", sortOrder: "0", isActive: true };
const emptyItem = { id: "", categoryId: "", name: "", description: "", priceNgn: "", sortOrder: "0", isActive: true };

export function FastErrandsAdminQueue() {
  const [errands, setErrands] = useState<Errand[]>([]); const [businesses, setBusinesses] = useState<Business[]>([]); const [catalog, setCatalog] = useState<FastErrandsCategory[]>([]); const [fulfilmentBusinessId, setFulfilmentBusinessId] = useState("");
  const [category, setCategory] = useState(emptyCategory); const [item, setItem] = useState(emptyItem); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const selectedBusiness = useMemo(() => businesses.find((business) => business.id === fulfilmentBusinessId), [businesses, fulfilmentBusinessId]);

  async function load() { setLoading(true); try { const response = await fetch("/api/admin/fast-errands", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Could not load FastErrands."); setErrands(data.errands || []); setBusinesses(data.businesses || []); setCatalog(data.catalog || []); setFulfilmentBusinessId(data.fulfilmentBusinessId || ""); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not load FastErrands."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);

  async function save(action: string, body: Record<string, unknown>, label: string) { setBusy(action); setMessage(null); try { const response = await fetch("/api/admin/fast-errands", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...body }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || `Could not save ${label}.`); if (data.catalog) setCatalog(data.catalog); if (data.fulfilmentBusinessId) setFulfilmentBusinessId(data.fulfilmentBusinessId); setMessage(`${label} saved.`); } catch (error) { setMessage(error instanceof Error ? error.message : `Could not save ${label}.`); } finally { setBusy(null); } }
  async function fund(errand: Errand) { setBusy(errand.id); setMessage(null); try { const response = await fetch("/api/admin/fast-errands", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ errandId: errand.id, actualPurchaseNgn: errand.purchase_budget_ngn, transferReference: `legacy-${errand.errand_code}` }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Could not fund vendor."); setMessage(`${errand.errand_code} vendor funded.`); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not fund vendor."); } finally { setBusy(null); } }

  return <main className="section-wrap pb-12 pt-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><span className="text-xs font-black uppercase tracking-[0.16em] text-fleet-ember">Admin control</span><h1 className="mt-1 text-3xl font-black text-fleet-night">FastErrands catalogue</h1><p className="mt-2 max-w-2xl text-sm font-semibold leading-6 text-slate-600">Manage customer-visible categories and prices, then send paid FastErrands to one existing business account.</p></div><div className="flex gap-2"><LinkButton href="/admin" variant="secondary">Admin dashboard</LinkButton><Button variant="secondary" onClick={load} disabled={loading}><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />Refresh</Button></div></div>{message ? <div className="mt-5 rounded-fleet bg-amber-50 p-3 text-sm font-bold text-amber-900">{message}</div> : null}

    <Card className="mt-6 p-5"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-fleet bg-orange-50 text-fleet-ember"><Store className="h-5 w-5" /></span><div><h2 className="text-xl font-black text-fleet-night">FastErrands fulfilment account</h2><p className="mt-1 text-sm font-semibold text-slate-500">Paid catalogue orders appear in this existing business account&apos;s dashboard and wallet.</p></div></div><div className="mt-4 flex flex-col gap-3 sm:flex-row"><select className="form-input flex-1" value={fulfilmentBusinessId} onChange={(event) => setFulfilmentBusinessId(event.target.value)}><option value="">Select an active business account</option>{businesses.map((business) => <option key={business.id} value={business.id}>{business.business_name} · {business.operating_state || business.pickup_address || "Location pending"}</option>)}</select><Button onClick={() => void save("set-fulfilment-business", { businessProfileId: fulfilmentBusinessId }, "Fulfilment account")} disabled={busy === "set-fulfilment-business" || !fulfilmentBusinessId}>{busy === "set-fulfilment-business" ? <Loader2 className="h-4 w-4 animate-spin" /> : <ShieldCheck className="h-4 w-4" />}Save account</Button></div>{selectedBusiness ? <p className="mt-3 text-xs font-bold text-emerald-700">Current account: {selectedBusiness.business_name}</p> : null}</Card>

    <div className="mt-6 grid gap-5 lg:grid-cols-2"><Card className="p-5"><div className="flex items-center gap-3"><PackagePlus className="h-5 w-5 text-fleet-ember" /><div><h2 className="text-xl font-black text-fleet-night">Categories</h2><p className="text-xs font-bold text-slate-500">Create or update what customers can browse.</p></div></div><div className="mt-4 grid gap-3"><input className="form-input" value={category.name} onChange={(event) => setCategory({ ...category, name: event.target.value })} placeholder="Category name" /><div className="grid gap-3 sm:grid-cols-[90px_1fr]"><input className="form-input" value={category.emoji} onChange={(event) => setCategory({ ...category, emoji: event.target.value })} placeholder="Emoji" /><input className="form-input" value={category.sortOrder} onChange={(event) => setCategory({ ...category, sortOrder: event.target.value.replace(/\D/g, "") })} placeholder="Sort order" inputMode="numeric" /></div><textarea className="form-input min-h-20" value={category.description} onChange={(event) => setCategory({ ...category, description: event.target.value })} placeholder="Short customer description" /><label className="flex items-center gap-2 text-sm font-bold text-fleet-night"><input type="checkbox" checked={category.isActive} onChange={(event) => setCategory({ ...category, isActive: event.target.checked })} />Visible to customers</label><div className="flex gap-2"><Button className="flex-1" onClick={() => void save("save-category", category, "Category")} disabled={busy === "save-category" || category.name.trim().length < 2}>{busy === "save-category" ? <Loader2 className="h-4 w-4 animate-spin" /> : null}{category.id ? "Update category" : "Add category"}</Button>{category.id ? <Button variant="secondary" onClick={() => setCategory(emptyCategory)}>Cancel</Button> : null}</div></div><div className="mt-5 grid gap-2">{catalog.map((entry) => <button key={entry.id} type="button" onClick={() => setCategory({ id: entry.id, name: entry.name, description: entry.description || "", emoji: entry.emoji || "", sortOrder: String(entry.sort_order), isActive: entry.is_active })} className="flex items-center justify-between rounded-fleet bg-fleet-paper p-3 text-left"><span><strong className="block text-sm font-black text-fleet-night">{entry.emoji || "📦"} {entry.name}</strong><span className="text-xs font-semibold text-slate-500">{entry.items.length} items · {entry.is_active ? "Visible" : "Hidden"}</span></span><Pencil className="h-4 w-4 text-fleet-ember" /></button>)}</div></Card>
      <Card className="p-5"><div className="flex items-center gap-3"><WalletCards className="h-5 w-5 text-fleet-ember" /><div><h2 className="text-xl font-black text-fleet-night">Priced items</h2><p className="text-xs font-bold text-slate-500">The server rechecks these prices at checkout.</p></div></div><div className="mt-4 grid gap-3"><select className="form-input" value={item.categoryId} onChange={(event) => setItem({ ...item, categoryId: event.target.value })}><option value="">Choose category</option>{catalog.map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select><input className="form-input" value={item.name} onChange={(event) => setItem({ ...item, name: event.target.value })} placeholder="Item name" /><div className="grid gap-3 sm:grid-cols-2"><input className="form-input" value={item.priceNgn} onChange={(event) => setItem({ ...item, priceNgn: event.target.value.replace(/\D/g, "") })} placeholder="Price (₦)" inputMode="numeric" /><input className="form-input" value={item.sortOrder} onChange={(event) => setItem({ ...item, sortOrder: event.target.value.replace(/\D/g, "") })} placeholder="Sort order" inputMode="numeric" /></div><textarea className="form-input min-h-20" value={item.description} onChange={(event) => setItem({ ...item, description: event.target.value })} placeholder="Optional item detail" /><label className="flex items-center gap-2 text-sm font-bold text-fleet-night"><input type="checkbox" checked={item.isActive} onChange={(event) => setItem({ ...item, isActive: event.target.checked })} />Available for checkout</label><div className="flex gap-2"><Button className="flex-1" onClick={() => void save("save-item", item, "Item")} disabled={busy === "save-item" || !item.categoryId || item.name.trim().length < 2 || !Number(item.priceNgn)}>{busy === "save-item" ? <Loader2 className="h-4 w-4 animate-spin" /> : null}{item.id ? "Update item" : "Add item"}</Button>{item.id ? <Button variant="secondary" onClick={() => setItem(emptyItem)}>Cancel</Button> : null}</div></div><div className="mt-5 grid gap-2">{catalog.flatMap((entry) => entry.items.map((catalogItem) => <button key={catalogItem.id} type="button" onClick={() => setItem({ id: catalogItem.id, categoryId: entry.id, name: catalogItem.name, description: catalogItem.description || "", priceNgn: String(catalogItem.price_ngn), sortOrder: String(catalogItem.sort_order), isActive: catalogItem.is_active })} className="flex items-center justify-between rounded-fleet bg-fleet-paper p-3 text-left"><span><strong className="block text-sm font-black text-fleet-night">{catalogItem.name}</strong><span className="text-xs font-semibold text-slate-500">{entry.name} · {catalogItem.is_active ? "Available" : "Hidden"}</span></span><span className="flex items-center gap-3"><b className="text-sm text-fleet-night">{formatMoney(catalogItem.price_ngn)}</b><Pencil className="h-4 w-4 text-fleet-ember" /></span></button>))}</div></Card></div>

    {errands.length ? <Card className="mt-6 p-5"><h2 className="text-xl font-black text-fleet-night">Legacy FastErrands funding</h2><p className="mt-1 text-sm font-semibold text-slate-500">Orders created before the catalogue launch remain protected and can be completed here.</p><div className="mt-4 grid gap-3">{errands.filter((errand) => errand.status === "funded_waiting_admin").map((errand) => <div key={errand.id} className="flex flex-col gap-3 rounded-fleet bg-fleet-paper p-3 sm:flex-row sm:items-center sm:justify-between"><span><strong className="block text-sm font-black text-fleet-night">{errand.errand_code} · {errand.vendor_name}</strong><span className="text-xs font-bold text-slate-500">{formatMoney(errand.customer_total_ngn)} · {errand.deliveries?.dropoff_address || "Address pending"}</span></span><Button size="sm" onClick={() => void fund(errand)} disabled={busy === errand.id}>{busy === errand.id ? <Loader2 className="h-4 w-4 animate-spin" /> : null}Fund legacy order</Button></div>)}</div></Card> : null}
  </main>;
}
